backend:
  name: github
  repo: lipengqing96/my-blog
  branch: main
  base_url:https://api.netlify.com
  auth_endpoint: /auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}
